server:
  port: ${PORT:8081}

spring:
  application:
    name: microservice-stateless-any-api

app:
  token:
    secret-key: ${JWT_SECRET:Y3Vyc28tYXV0ZW50aWNhY2FvLXN0YXRlZnVsLXN0YXRlbGVzcy1taXJvc3NlcnZpY29zLWRhbnRhcw==}